### ISSUE TITLE
Check non-flatness

### ISSUE THREAD

**Issue by chmnk** [maabuu/posebusters#53]
Some models predict non-flat sp3 rings as flat aromatic ones, as for some sets of atoms aromatic rings prevail in the training set. Would be nice to have a non-flatness check. 

I'd be happy to commit this, but not sure what way would you prefer? Making a new file for non-flatness, making a new function, or just adding an option to choose between <= or >= operators to the `check_flatness`?

**Comment by maabuu** [comment]
Great idea. I welcome a PR on this. I would prefer the last option, that is adding an option to the `flatness` function to reuse it for non-flat systems as shown below. I am unsure about the threshold or the SMARTS here - maybe you have some example SMARTS or systems in mind? 

Candidate non-flatness config for rings
```yaml
  - name: "Ring non-flatness"
    function: "flatness"
    parameters:
      flat_systems: # list atoms which together should lie on plane as SMARTS matches
        nonaromatic_5_membered_rings_sp3: "[C,N&!a]1[C,N&!a][C,N&!a][C,N&!a][C,N&!a]1"
        nonaromatic_6_membered_rings_sp3: "[C,N&!a]1[C,N&!a][C,N&!a][C,N&!a][C,N&!a][C,N&!a]1"
      threshold_flatness: 0.25 # max distance in A to closest shared plane
      check_nonflat: True
    chosen_binary_test_output:
      - flatness_passes
    rename_outputs:
      num_systems_checked: number_aromatic_rings_checked
      num_systems_passed: number_aromatic_rings_pass
      max_distance: aromatic_ring_maximum_distance_from_plane
      flatness_passes: "Aromatic ring flatness"
```

Existing flatness config for rings
```yaml
  - name: "Ring flatness"
    function: "flatness"
    parameters:
      flat_systems: # list atoms which together should lie on plane as SMARTS matches
        aromatic_5_membered_rings_sp2: "[ar5^2]1[ar5^2][ar5^2][ar5^2][ar5^2]1"
        aromatic_6_membered_rings_sp2: "[ar6^2]1[ar6^2][ar6^2][ar6^2][ar6^2][ar6^2]1"
      threshold_flatness: 0.25 # max distance in A to closest shared plane
    chosen_binary_test_output:
      - flatness_passes
    rename_outputs:
      num_systems_checked: number_aromatic_rings_checked
      num_systems_passed: number_aromatic_rings_pass
      max_distance: aromatic_ring_maximum_distance_from_plane
      flatness_passes: "Aromatic ring flatness"
```
